// Lista canónica de barrios de Cali extraída de mc_barrios.shp (339 barrios)
// Usada en el prompt de OpenAI para que la extracción de barrio devuelva nombres normalizados.
export const BARRIOS_CALI: string[] = [
  "20 de Julio","3 de Julio","Aguablanca","Aguacatal","Alameda","Alfonso Barberena A.",
  "Alfonso Bonilla Aragón","Alfonso Lopez P. 1a Etapa","Alfonso Lopez P. 2a Etapa",
  "Alfonso Lopez P. 3a Etapa","Alférez Real","Alirio Mora Beltrán","Alto Normandia",
  "Alto Nápoles","Altos de Menga","Antonio Nariño","Aranjuez","Arboledas","Asturias",
  "Atanasio Girardot","Barrio Obrero","Base Aérea","Belalcázar","Belisario Caicedo",
  "Bellavista","Bello Horizonte","Belén","Benjamín Herrera","Bolivariano",
  "Bosques del Limonar","Bretaña","Brisas de Los Alamos","Brisas de Mayo",
  "Brisas del Limonar","Buenos Aires","Caldas","Calima","Calimio Desepaz","Calipso",
  "Camino Real - Joaquin Borrero Sinisterra","Camino Real - Los Fundadores","Caney",
  "Cañaveral","Cañaveralejo - Seguros Patria","Cañaverales - Los Samanes","Centenario",
  "Champagnat","Chapinero","Charco Azul","Chiminangos I","Chiminangos II","Chipichape",
  "Ciudad 2000","Ciudad Campestre","Ciudad Capri","Ciudad Córdoba","Ciudad Talanga",
  "Ciudad Universitaria","Ciudad de Los Alamos","Ciudadela Comfandi","Ciudadela Floralia",
  "Ciudadela Pasoancho","Ciudadela del Rio - CVC","Club Campestre","Colinas del Sur",
  "Colseguros Andes","Compartir","Cristóbal Colón","Cuarteles de Nápoles",
  "Cuarto de Legua - Guadalupe","Departamental","Desepaz Invicali","Doce de Octubre",
  "Eduardo Santos","El Bosque","El Calvario","El Cedro","El Cortijo","El Diamante",
  "El Dorado","El Gran Limonar","El Gran Limonar - Cataya","El Guabal","El Hoyo",
  "El Ingenio","El Jardín","El Jordán","El Lido","El Limonar","El Morichal","El Mortiñal",
  "El Nacional","El Paraíso","El Peñón","El Piloto","El Poblado I","El Poblado II",
  "El Pondaje","El Prado","El Recuerdo","El Refugio","El Remanso","El Retiro","El Rodeo",
  "El Sena","El Troncal","El Trébol","El Vallado","El Vergel","Eucaristico","Evaristo Garcia",
  "Fenalco Kennedy","Fepicol","Flora Industrial","Fonaviemcali","Francisco Eladio Ramírez",
  "Fátima","Granada","Guayaquil","Guillermo Valencia","Horizontes","Ignacio Rengifo",
  "Industria de Licores","Industrial","Jorge Eliécer Gaitán","Jorge Isaacs",
  "Jorge Zawadsky","José Holguín Garcés","José Manuel Marroquín I","José Manuel Marroquín II",
  "José María Córdoba","Juanambú","Julio Rincón","Junín","La Alborada","La Alianza",
  "La Base","La Campiña","La Cascada","La Esmeralda","La Esperanza","La Flora",
  "La Floresta","La Fortaleza","La Gran Colombia","La Hacienda","La Independencia",
  "La Isla","La Libertad","La Merced","La Paz","La Playa","La Rivera I","La Selva",
  "La Sultana","Las Acacias","Las Américas","Las Ceibas","Las Delicias","Las Granjas",
  "Las Orquídeas","Las Quintas de Don Simón","Laureano Gómez","León XIII","Lili",
  "Lleras Camargo","Lleras Restrepo","Lleras Restrepo II","Los Alcazares Primera Etapa",
  "Los Alcazares Segunda Etapa","Los Alcazares Tercera Etapa","Los Andes",
  "Los Andes B - La Riviera","Los Chorros","Los Comuneros I","Los Comuneros II",
  "Los Conquistadores","Los Cámbulos","Los Farallones","Los Guaduales","Los Guayacanes",
  "Los Lagos","Los Libertadores","Los Lideres","Los Naranjos","Los Naranjos II",
  "Los Parques Barranquilla","Los Pinos","Los Portales - Nuevo Rey","Los Robles",
  "Los Sauces","Lourdes","Manuel Maria Buenaventura","Manuela Beltrán","Manzanares",
  "Maracaibo","Marco Fidel Suárez","Mariano Ramos","Mario Correa Rengifo","Marroquín III",
  "Mayapan - Las Vegas","Meléndez","Menga","Metropolitano del Norte","Miraflores","Mojica",
  "Municipal","Navarro - La Chanca","Normandia","Nueva Floresta","Nueva Tequendama",
  "Nápoles","Olaya Herrera","Olímpico","Omar Torrijos","Pampa Linda","Panamericano",
  "Parcelaciones Pance","Parque de la Caña","Paseo de Los Almendros","Paso del Comercio",
  "Pasoancho","Petecuy Primera Etapa","Petecuy Segunda Etapa","Petecuy Tercera Etapa",
  "Pizamos I","Pizamos II","Pizamos III - Las Dalias","Planta de Tratamiento","Polvorines",
  "Popular","Portada de Comfandi - Las Encinas","Porvenir","Potrero Grande",
  "Prados de Oriente","Prados del Limonar","Prados del Norte","Prados del Sur",
  "Primavera","Primero de Mayo","Primitivo Crespo","Promociones Populares B","Pueblo Joven",
  "Puerta del Sol","Puerto Mallarino","Puerto Nuevo","Rafael Uribe Uribe",
  "República de Israel","Ricardo Balcázar","Rodrigo Lara Bonilla","Saavedra Galindo",
  "Salomia","San Antonio","San Benito","San Carlos","San Cayetano","San Cristóbal",
  "San Fernando Nuevo","San Fernando Viejo","San Juan Bosco","San Judas Tadeo I",
  "San Judas Tadeo II","San Luis","San Luis II","San Marino","San Nicolás","San Pascual",
  "San Pedro","San Pedro Claver","San Vicente","Santa Anita - La Selva","Santa Bárbara",
  "Santa Elena","Santa Fé","Santa Isabel","Santa Mónica","Santa Mónica Belalcázar",
  "Santa Mónica Popular","Santa Rita","Santa Rosa","Santa Teresita","Santander",
  "Santo Domingo","Sector Alto Jordán","Sector Alto de los Chorros",
  "Sector Altos de Santa Isabel","Sector Asprosocial - Diamante",
  "Sector Cañaveralejo Guadalupe","Sector Laguna del Pondaje","Sector Meléndez",
  "Sector Patio Bonito","Sector Puente del Comercio","Senderos de La Flora",
  "Siete de Agosto","Siloé","Simón Bolívar","Sindical","Sucre",
  "Sultana - Berlín - San Francisco","Tejares - Cristales","Terron Colorado",
  "Tierra Blanca","Torres de Comfandi","U. D. A. Galindo Plaza de Toros",
  "Ulpiano Lloreda","Unicentro Cali","Unidad Deportiva Jaime Aparicio",
  "Unidad Residencial Bueno Madrid","Unidad Residencial El Coliseo",
  "Unidad Residencial Santiago de Cali","Unión de Vivienda Popular",
  "Urbanización Boyaca","Urbanización Calimio","Urbanización Ciudad Jardín",
  "Urbanización Colseguros","Urbanización El Angel del Hogar","Urbanización La Flora",
  "Urbanización La Merced","Urbanización La Nueva Base","Urbanización Militar",
  "Urbanización Nueva Granada","Urbanización Rio Lili","Urbanización San Joaquin",
  "Urbanización Tequendama","Valle Grande","Vendimia",
  "Venezuela - Urbanización Cañaveralejo","Versalles","Villa Colombia","Villa del Lago",
  "Villa del Prado - El Guabito","Villa del Sol","Villa del Sur","Villablanca",
  "Villamercedes I - Villa Luz - Las Garzas","Villanueva","Vipasa","Vista Hermosa",
  "Yira Castro",
];
